### ISSUE TITLE
Sayitni main qismidagi  hero-content qismida text da css berisda hatolik bor

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/akademnashr-selfmade#1]
https://prnt.sc/UF-kxbDBAtJN
bu yerda **margin-bottom** ga qarab qo'ying 
shu yerda linkga **display: inline-block;** qilib qo'ysayiz bo'ldi

**Comment by MIRZOULUGBEK9008** [comment]
Rahmat baratan to'g'rilandi.
