### ISSUE TITLE
Sayitni hero-three-action qismida textlarga css berish hato

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/akademnashr-selfmade#2]
https://github.com/MIRZOULUGBEK9008/akademnashr-selfmade/blob/11ac6f649f438eb2eb60dc8915a8989a6d7140ea/index.html#L108
margin-top:0; teng qilish kerak keyin margin-bottomga etibor berib qo'ying
https://prnt.sc/SJbYUoAPqUVM

**Comment by MIRZOULUGBEK9008** [comment]
#fix
